### ISSUE TITLE
IDE suggestion? Orientation?

### ISSUE THREAD

**Issue by dckc** [rchain/Rosette#15]
I'm struggling to find my way around in this code; for example, atop Ob.scala I see:
```
import shapeless._
```

which means any name in the file may or may not come from that import -- I can't follow my nose just by looking at this file.

I mostly use emacs, but thinking perhaps and IDE would help me navigate, I tried IntelliJ IDEA, but due to [SCL-8710](https://youtrack.jetbrains.com/issue/SCL-8710) it gets very confused about lenses. It finds 95 errors in `VirtualMachine.scala`, even though the code compiles just fine.

Do you use any tools or do you just keep all the types and imports in your head?

**Comment by jeamick** [comment]
Hi , I think we could use emacs for now ! I use emacs too !

**Comment by dckc** [comment]
I learned that a couple of the developers just use emacs with syntax highlighting.
